# Generated by Django 4.2 on 2026-03-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Codigo')),
                ('description', models.CharField(max_length=45, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('description', models.CharField(max_length=45, verbose_name='Descripción')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.continent', verbose_name='Continente')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Código')),
                ('description', models.CharField(max_length=45, verbose_name='Descripción')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.country', verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Código')),
                ('description', models.CharField(max_length=45, verbose_name='Descripción')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.department', verbose_name='Departamento')),
            ],
        ),
    ]
