# Generated by Django 4.2 on 2026-02-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=45)),
                ('continentes', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuracion.continentes')),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=45)),
                ('departamentos', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuracion.departamentos')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='paises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuracion.paises'),
        ),
    ]
